### ISSUE TITLE
Add 'data' and 'Rust' to terminology list (include gender, for the benefit of future translators?)

### ISSUE THREAD

**Issue by IttayWeiss** [IttayWeiss/rustbook-heb#16]
'Data' and 'Rust' are missing in the current terminology list. Their gender, masculine and feminine respectively, could be added to help future translators. However, in the finalised translated book, it would seem odd to include the gender in the list. So, perhaps the gender should be left out.

**Comment by IdanLib** [comment]
I agree on the "gender policy" here. We can take it out once the main translation work is over (that is, we have an initial full Hebrew translation of the book).
Added Data and Rust to the terminology.

**Comment by IdanLib** [comment]
Done
