### ISSUE TITLE
Missing translation of last few pars in 9.3

### ISSUE THREAD

**Issue by IdanLib** [IttayWeiss/rustbook-heb#43]
The last few paragraphs of chapter 09-03 have not been translated, probably due to some sort of omission. @IttayWeiss let me know if you have time to do it.

**Comment by IdanLib** [comment]
Not sure I follow - there's no active PR for chapter 09 (though there is one for chapter 19). I had approved the Chap09 before editing it (I browsed it, but I probably should have looked at it more closely).

**Comment by IttayWeiss** [comment]
Oh, I see. No worries. I was confused since Issue #36 is still open. Did you by any chance merge the PR for Chapter 09? In any case, I will go ahead now and finish the translation of 09-03.

**Comment by IdanLib** [comment]
Corrected. edited, PR opened for chapter 9 reviewed
