### ISSUE TITLE
Double check last few paragraphs of the edited version of Chapter 9

### ISSUE THREAD

**Issue by IttayWeiss** [IttayWeiss/rustbook-heb#47]
There was a conflict to resolve during the PR of the edit to Chapter 9. Action taken was to merge by accepting all incoming changes. It would be a good idea to double check that after the merge. So, that simply means carefully reading the last 2-3 paragraphs, and comparing to original book.

**Comment by IdanLib** [comment]
Cool, doing that now.

**Comment by IdanLib** [comment]
So, I checked again and made some minor editing changes (really just for style). I created a new branch for it (but haven't created a PR; I can do that if need be). 

You can review the existing text on main, or the new branch, which is here: 
https://github.com/IttayWeiss/rustbook-heb/blob/IdanL_chap09.3_extra_review/src/ch09-03-to-panic-or-not-to-panic.md
(re-edited paragraphs are those just below figure 9-13. 
Or make any changes yourself if you deem fit. Whatever works :)

**Comment by IdanLib** [comment]
It has been merged, correct?
Can I close this issue?

**Comment by IttayWeiss** [comment]
Yes, indeed. I'll close it now.
